@echo off

set ENVIRONMENT_ENV_VAR=dev
set DEFAULT_ADMIN_TOKEN_ENV_VAR=
set COOKIE_SECRET_ENV_VAR=
set HOST_ENV_VAR=
set HOST_PORT_ENV_VAR=
set MONGODB_CONNECTION_URI_ENV_VAR=
set MONGODB_DATABASE_ENV_VAR=
set MONGODB_USERS_COLL_ENV_VAR=