GENERAL:
  ENVIRONMENT: ${ENVIRONMENT_ENV_VAR}
  DEFAULT_ADMIN_TOKEN: ${DEFAULT_ADMIN_TOKEN_ENV_VAR}
  COOKIE_SECRET: ${COOKIE_SECRET_ENV_VAR}
  HOST: ${HOST_ENV_VAR}:DEFAULT:localhost
  PORT: ${HOST_PORT_ENV_VAR}:DEFAULT:8080

DATABASE:
  CONNECTION_URI: ${MONGODB_CONNECTION_URI_ENV_VAR}
  DDBB: ${MONGODB_DATABASE_ENV_VAR}
  USERS_COLLECTION: ${MONGODB_USERS_COLL_ENV_VAR}
